"""chave estrangeira

Revision ID: 40fbfaf2b6b9
Revises: 
Create Date: 2024-11-30 15:47:31.644187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40fbfaf2b6b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conteudo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_modulo', sa.Integer(), nullable=True))
        batch_op.alter_column('titulo',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('subtitulo',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('texto',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('slug',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.create_foreign_key(None, 'modulo', ['id_modulo'], ['id_modulo'])

    with op.batch_alter_table('modulo', schema=None) as batch_op:
        batch_op.alter_column('titulo',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('descricao',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modulo', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('titulo',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('conteudo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('slug',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('texto',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('subtitulo',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('titulo',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('id_modulo')

    # ### end Alembic commands ###
